---
environment_path: "../setup/rrAvbnwiDltxh6Ge3CeWl"
use_dangerous_test_keystore: false
dpki: ~
keystore_path: "../setup/rrAvbnwiDltxh6Ge3CeWl/keystore"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 0
network: ~
