---
environment_path: "../setup/c9WFXz0YDDHQdpYAUwCk4"
use_dangerous_test_keystore: false
dpki: ~
keystore_path: "../setup/c9WFXz0YDDHQdpYAUwCk4/keystore"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 0
network: 
  transport_pool:
  - type: quic
    bind_to: ~
    override_host: ~
    override_port: ~
bootstrap_service: ~
tuning_params:
  gossip_loop_iteration_delay_ms: "10"
  default_notify_remote_agent_count: "5"
  default_notify_timeout_ms: "30000"
  default_rpc_single_timeout_ms: "30000"
  default_rpc_multi_remote_agent_count: "2"
  default_rpc_multi_timeout_ms: "30000"
  agent_info_expires_after_ms: "1200000"
  tls_in_mem_session_storage: "512"
  proxy_keepalive_ms: "120000"
  proxy_to_expire_ms: "300000"
  concurrent_limit_per_thread: "32"
  tx2_quic_max_idle_timeout_ms: "30000"
  tx2_pool_max_connection_count: "4096"
  tx2_channel_count_per_connection: "3"
  tx2_implicit_timeout_ms: "30000"
  tx2_initial_connect_retry_delay_ms: "200"
network_type: quic_bootstrap