[workspace]
members = [
"zomes/chess",
"zomes/profiles",
"zomes/invitations",
]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[patch.crates-io]
holochain_turn_based_game = {path="../../holochain-turn-based-game/"}