[package]
name = "invitations"
version = "0.0.1"
authors = [ "manuel_puentes" ]
edition = "2018"

[lib]
name = "invitations"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
invitations = {git = "https://github.com/ManuelPuentes/Invitations_zome.git", package = "invitation" , branch =  "master"}
