[package]
authors = ["manuel_puentes"]
edition = "2018"
name = "hc_zome_invitations"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_invitations"

[dependencies]
invitations = {path = "../../../../invitations_zome/zome/zomes/invitations/"}
