[package]
authors = ["manuel_puentes"]
edition = "2018"
name = "invitations"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "invitations"

[dependencies]
hc_zome_invitations = {git = "https://github.com/eyss/invitations", rev = "8571033b0d2bfe5ef09dd39bc4a134ed7fedf8f4"}
