---
environment_path: "../setup/hdi5W3fT3mDXgqhRy6Stn"
use_dangerous_test_keystore: false
dpki: ~
keystore_path: "../setup/hdi5W3fT3mDXgqhRy6Stn/keystore"
passphrase_service: ~
admin_interfaces:
  - driver:
      type: websocket
      port: 0
network: ~
