[package]
authors = ["manuel_puentes"]
edition = "2018"
name = "hc_chess_zome"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_chess_zome"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}

hdk = "0.0.100"
holo_hash = "0.0.2-alpha.1"

holochain_turn_based_game = "0.2.3"
chess = "3.2.0"
