[package]
authors = ["manuel_puentes"]
edition = "2018"
name = "chess"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "chess"

[dependencies]
chess = "3.2.0"
derive_more = "0"
hdk = "0.0.100"
holo_hash = "0.0.2-alpha.1"
holochain_turn_based_game = "0.2.2"
serde = "1"
