[package]
authors = ["manuel_puentes"]
edition = "2018"
name = "hc_zome_chess"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "hc_zome_chess"

[dependencies]
chrono = {version = "0.4", features = ["serde"]}
derive_more = "0"
serde = "1"

hdk = "0.0.107"
holo_hash = {version = "0.0.7", features = ["encoding"]}

chess = "3.2.0"
hc_turn_based_game = {git = "http://github.com/eyss/hc-turn-based-game", rev = "6b8acbaac5b43041f979e02dfded227de5791176"}
